### ISSUE TITLE
terkena captcha mint host di heroku

### ISSUE THREAD

**Issue by riskyprsty** [hansputera/brainly-scraper-languages#1]

**Comment by hansputera** [comment]
Iya gan, saya juga lagi cari cara supaya tidak terkena captcha

**Comment by EmangGek** [comment]
di repl juga kena captcha min

**Comment by hansputera** [comment]
Nanti saya coba koreksi lagi ya, terimakasih!

**Comment by hansputera** [comment]
Halo @riskyprsty @EmangGek ini silahkan coba versi branch [dev](https://github.com/hansputera/brainly-scraper-languages/tree/dev).

**Comment by hansputera** [comment]
https://repl.it/@hansputera/NextDimpledFeed

Untuk Example nya disini, bisa kok 😄

**Comment by hansputera** [comment]
Tidak kena captcha

**Comment by hansputera** [comment]
Maaf, saya baru coba di glitch, dan heroku masih terkena captcha. Tapi tadi saya sudah coba di Repl.it sudah tidak.

**Comment by EmangGek** [comment]
makasih gan

**Comment by hansputera** [comment]
> makasih gan

Di repl.it nampak nya udah fix

**Comment by Kry9toN** [comment]
Di termux masih error `403`

**Comment by hansputera** [comment]
Sudah ditambahkan opsi negara sehingga sisa memilih negara yang sesuai, jangan lupa baca readme. Terimakasih.
