### ISSUE TITLE
TypeError: Brainly is not a constructor

### ISSUE THREAD

**Issue by frmdeveloper** [hansputera/brainly-scraper-languages#11]
new Brainly

```sh
TypeError: Brainly is not a constructor
    at eval (eval at <anonymous> (/root/frmwaapi/index.js:371:17), <anonymous>:2:15)
    at eval (eval at <anonymous> (/root/frmwaapi/index.js:371:17), <anonymous>:4:43)
    at EventEmitter.<anonymous> (/root/frmwaapi/index.js:371:17)
    at EventEmitter.emit (events.js:412:35)
    at WebSocket.<anonymous> (/root/frmwaapi/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:389:16)
```

**Comment by OhYoonHee** [comment]
@frmdeveloper

**Comment by hansputera** [comment]
New example code:

```ts
import { Brainly } from 'brainly-scraper-v2';
```
or
```js
const { Brainly } = require('brainly-scraper-v2');
```

**Comment by ridhwan-aziz** [comment]
@OhYoonHee TEST

**Comment by thoriqazzikraa** [comment]
> New example code:
> 
> ```ts
> import { Brainly } from 'brainly-scraper-v2';
> ```
> 
> or
> 
> ```js
> const { Brainly } = require('brainly-scraper-v2');
> ```

![Screenshot_2022-10-14-13-00-24-65_375f2148cf8fa4d7b3a7c6a3ff0c7e6c](https://user-images.githubusercontent.com/89589243/195773373-846e4005-47a4-45ec-bc56-4ec863f42a66.jpg)

**Comment by hansputera** [comment]
Please upgrade `brainly-scraper-v2` to the latest version.

**Comment by thoriqazzikraa** [comment]
> Please upgrade `brainly-scraper-v2` to the latest version.

![Screenshot_2022-10-14-22-53-16-04_375f2148cf8fa4d7b3a7c6a3ff0c7e6c](https://user-images.githubusercontent.com/89589243/195889114-50d2ae2b-0c6b-4720-bcc2-757ae80f2004.jpg)

**Comment by hansputera** [comment]
> > Please upgrade `brainly-scraper-v2` to the latest version.
> 
> ![Screenshot_2022-10-14-22-53-16-04_375f2148cf8fa4d7b3a7c6a3ff0c7e6c](https://user-images.githubusercontent.com/89589243/195889114-50d2ae2b-0c6b-4720-bcc2-757ae80f2004.jpg)
> 

![IMG_20221015_001743.jpg](https://user-images.githubusercontent.com/47862061/195893797-ece702af-fd6a-4c50-8b9c-ee44242c8e52.jpg)
