### ISSUE TITLE
There somthing wrong 

### ISSUE THREAD

**Issue by officialdittaz** [hansputera/brainly-scraper-languages#15]
![Screenshot_2022-02-21-18-15-38-347_com whatsapp](https://user-images.githubusercontent.com/86673643/154945753-0e75527e-aa1e-44d2-8a03-5c21d699d537.jpg)

Here my script
case 'brainly':{
if (isLimit(senderNumber, isPremium, isOwner, limitCount, user)) return reply (`Limit kamu sudah habis silahkan kirim ${prefix}limit untuk mengecek limit`)
if (!q) setReply( 'Soalnya?')
nana =`https://www.logosvgpng.com/wp-content/uploads/2018/04/brainly-logo-vector.png`
foto = await getBuffer(nana)   
let res = await brainly.search('id', `${q}`)
teks =`_*BRAINLY*_\n\n`
//let toks = res.map((v, i) => `${v.question.content}\n${e.answers.map((v,i) => `*JAWABAN KE ${i + 1}*\n${v}\n`)}\n\n═════════════════\n\n`)\n*Jurusan*: ${e.question.education}
//teks +=`${toks}`

res.map(function(e, i){
teks +=`_*PERTANYAAN KE ${i + 1}*_\n${e.question.content}\n${e.answers.map((v,i) => `*JAWABAN KE ${i + 1}*\n${v}\n`)}\n\n═════════════════\n\n`
 });
 
 teks +=`_Thanks for choosing Brainly_`
 
let mok = [{"buttonId": `Thanks`,"buttonText": {"displayText": `ᴛʜᴀɴᴋs`},"type": "RESPONSE"},
                    {"buttonId": `${prefix}donasi`,"buttonText": {"displayText": `ᴅᴏɴᴀsɪ`},"type": "RESPONSE"}]
sendButLocation(from, teks, `© ${fake1}`, foto, mok, {contextInfo: forward})             
limitAdd(senderNumber, user)
}
break

**Comment by hansputera** [comment]
Hello!
What's the problem? Can you explain?

**Comment by officialdittaz** [comment]
Hi i cant get The answer data, its just objecr - object, can you give example code, because my code not work,

**Comment by officialdittaz** [comment]
Here my code
let res = await brainly.search('id', `${q}`)

And the result :
{
    question: {
      id: 48793827,
      content: 'cari triple pytagoras dan bukan pytagoras​',
      closed: true,
      created: [Object],
      attachments: [Array],
      author: [Object],
      education: 'matematika',
      education_level: null,
      canBeAnswered: false,
      points_answer: [Object],
      points_question: 10,
      grade: 'Sekolah Menengah Pertama',
      lastActivity: '2022-01-28T13:44:51.000Z',
      verifiedAnswer: false,
      answers: [Array]
    },
    answers: [ [Object] ]
  },
  {

And i use this code for geting data
res.map(function(e, i){
teks +=`_*PERTANYAAN KE ${i + 1}*_\n${e.question.content}\n${e.answers.map((v,i) => `*JAWABAN KE ${i + 1}*\n${v}\n`)}\n\n═════════════════\n\n`
 });

And the result of answer data is objec obejct,

Done
Sory my bad language

**Comment by officialdittaz** [comment]
Susah kali

**Comment by hansputera** [comment]
Hello, thanks for the response.

- For the output of `[object object]`, you can read https://stackoverflow.com/a/57310111/13717698.
- And, don't forget to read the [docs](https://hansputera.github.io/brainly-scraper-languages/classes/Brainly.html#search)

Do you want an example? [Click here](https://github.com/hansputera/my-whatsapp-bot/blob/dev/src/commands/tools/brainly.ts)

**Comment by ridhwan-aziz** [comment]
@hansputera Thank you 😘

**Comment by officialdittaz** [comment]
Arigatou
