### ISSUE TITLE
Error with status code 403 running on heroku

### ISSUE THREAD

**Issue by officialdittaz** [hansputera/brainly-scraper-languages#16]
![IMG_20220223_061745](https://user-images.githubusercontent.com/86673643/155236061-d00c0735-3014-4f03-9f44-5284debbd8cd.jpg)

Gimana nih bwang kok error
Script :

const { Brainly } = require("brainly-scraper-v2");
const brainly = new Brainly("id"); 

case 'kuy':
await brainly.search('id', "Pythagoras").then(console.log).catch(console.error);
break

**Comment by hansputera** [comment]
Hello.

In the latest version, you can use `Brainly#searchWithMT` to avoid 403 Forbidden response. If you use `Brainly#search`, you must fill the country code correctly in the constructor.

**Comment by officialdittaz** [comment]
Oke makasih ya bwang :v

**Comment by ridhwan-aziz** [comment]
@officialdittaz sama sama

**Comment by officialdittaz** [comment]
Maap bwang, mau tanya lgi nih gua udah make
searchWithMT untuk memghindari error 403,
Saya coba di termux work dan muncul teksnya, pas di coba di heroku gada error sih tpi teksnya ga muncul, coba cek deh bwang
