### ISSUE TITLE
 Request failed with status code 403 di Heroku

### ISSUE THREAD

**Issue by Maru-Yasa** [hansputera/brainly-scraper-languages#4]
![error](https://user-images.githubusercontent.com/41475719/112742795-c7486980-8fbb-11eb-8ed3-44091116d032.png)

**Comment by hansputera** [comment]
Halo kak, terimakasih telah membuat issue di github repository ini. Namun, saya baru saja me-release versi terbaru dengan opsi pemilihan negara di constructor. Sehingga, kakak dapat memilih kode negara yang sesuai dengan lokasi server hosting kakak sendiri.

**Comment by hansputera** [comment]
Saya lihat, kakak menggunakan heroku ya? Heroku app nya region apa? Jika region United States, maka kode negara yang dimasukan ke dalam constructor ialah `us`. Terimakasih, silahkan mencoba.
