### ISSUE TITLE
Is this still active in dev?

### ISSUE THREAD

**Issue by Nurutomo** [hansputera/brainly-scraper-languages#5]
Please add axios options at 4th argument

**Comment by hansputera** [comment]
Hello, thank you for making an issue. Recently I have released the latest version on github with the country selection option so you can choose according to the location of your hosting server, and don't forget to read the readme.

**Comment by hansputera** [comment]
> Please add axios options at 4th argument

For what?

**Comment by Gimenz** [comment]
> > Please add axios options at 4th argument
> 
> For what?

for making axios request opstions, maybe?

**Comment by hansputera** [comment]
I do not use "axios" but "got". And, we've used "got" for this package.
