### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by whentheis** [hansputera/brainly-scraper-languages#50]
bang ini gmn ada eror
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
[AggregateError: All promises were rejected]
Node.js v17.1.0
````

vps ny di amerika jadi gua set ke us, pake conto ny di readme g bisa
```js
const { Brainly } = require("brainly-scraper-v2");
const brain = new Brainly("us");
 
brain.searchWithMT("Pythagoras", "id").then(console.log).catch(console.error);
```

kalo pake yg search cuma eror 403

**Comment by hansputera** [comment]
Halo, jika demikian, berarti gagal mendapatkan data dari semua jenis web brainly. Salah satu solusinya mungkin bisa menggunakan proxy. 

Untuk custom opsi request bisa dilakukan pada parameter ke 4 (`options`)
Sebagai contoh:
```js
const { Brainly } = require('brainly-scraper-v2');
const brain = new Brainly();

brain.searchWithMT("Pythagoras", "id", 10, {
 ...
});
```

Bagian `...` di-isi dengan opsi axios request pada biasanya. Untuk petunjuk mungkin bisa melihat https://stackoverflow.com/questions/57987119/how-to-set-proxy-when-using-axios-to-send-requests

**Comment by rushkii** [comment]
@hansputera MT itu apa?

**Comment by rushkii** [comment]
@rushkii

**Comment by hansputera** [comment]
> @hansputera MT itu apa?

Dari awal penamaan function sempat bingung, tetapi karena ini dia kerjanya berjalan menggunakan worker_threads, jadi MT saya definisikan sebagai Multi-Thread
