### ISSUE TITLE
Erros util

### ISSUE THREAD

**Issue by ghost** [hansputera/brainly-scraper-languages#67]
![Screenshot at 2022-12-10 23-54-24](https://user-images.githubusercontent.com/96320832/206866229-96d6d1dd-4628-49bc-a675-580a8ade6a3f.png)

**Comment by hansputera** [comment]
Hi, can you show your installed nodejs version?

**Comment by ghost** [comment]
> Hi, can you show your installed nodejs version?

$node
Welcome to Node.js v12.22.12.
Type ".help" for more information.
>

**Comment by ghost** [comment]
> Hi, can you show your installed nodejs version?

![Screenshot at 2022-12-12 01-54-11](https://user-images.githubusercontent.com/96320832/206923080-6d993b74-642d-47e0-b042-41d01b48bb28.png)

**Comment by hansputera** [comment]
> > Hi, can you show your installed nodejs version?
> 
> $node
> Welcome to Node.js v12.22.12.
> Type ".help" for more information.
> > 
> 
> 
> 
> 
> 
> 

Upgrade your NodeJS version to v14 or to the latest version.

**Comment by ghost** [comment]
> Owner



> > > Hi, can you show your installed nodejs version?
> > 
> > 
> > $node
> > Welcome to Node.js v12.22.12.
> > Type ".help" for more information.
> > >
> 
> Upgrade your NodeJS version to v14 or to the latest version.

$node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
>

**Comment by ghost** [comment]
> > > Hi, can you show your installed nodejs version?
> > 
> > 
> > $node
> > Welcome to Node.js v12.22.12.
> > Type ".help" for more information.
> > >
> 
> Upgrade your NodeJS version to v14 or to the latest version.

TypeError: json.map is not a function
    at /opt/lampp/htdocs/apicuy/scraper/brainly.js:7:23
GET /api/search/brainly?q=paparikan 200 2.399 ms - 88

**Comment by hansputera** [comment]
> > > > Hi, can you show your installed nodejs version?
> > > 
> > > 
> > > $node
> > > Welcome to Node.js v12.22.12.
> > > Type ".help" for more information.
> > > >
> > 
> > Upgrade your NodeJS version to v14 or to the latest version.
> 
> TypeError: json.map is not a function
>     at /opt/lampp/htdocs/apicuy/scraper/brainly.js:7:23
> GET /api/search/brainly?q=paparikan 200 2.399 ms - 88

You may check your code first, and try to debug the results.
