### ISSUE TITLE
[Bug] 403 Forbidden Request

### ISSUE THREAD

**Issue by evaasmakula** [hansputera/brainly-scraper-languages#9]
Error 403, semua kode bahasa sudah dicoba dan tetap menghasilkan error 403.

`BrainlyError: HTTPError: Response code 403 (Forbidden)
    at Brainly.<anonymous> (pg/node_modules/brainly-scraper-v2/src/main.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (pg/node_modules/brainly-scraper-v2/src/main.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by hansputera** [comment]
Halo, selamat malam dan terimakasih. 

Ada kode penggunaannya?

**Comment by evaasmakula** [comment]
> Halo, selamat malam dan terimakasih.
> 
> Ada kode penggunaannya?

Selamat malam juga kak, untuk kode penggunaan masih sama dengan dokumentasi, setelah penggunaan sekitaran 6 kali baru terjadi error 403.

**Comment by hansputera** [comment]
Lokasi (server/host) dimana?

**Comment by evaasmakula** [comment]
> Lokasi (server/host) dimana?

Kode 

`import Brainly from "brainly-scraper-v2";
const brain = new Brainly("id"); // 'id' - Default to 'id'

brain.search("es", "Pythagoras").then(console.log).catch(console.error);`

Console

`BrainlyError: HTTPError: Response code 403 (Forbidden)
    at Brainly.<anonymous> (/data/data/com.termux/files/home/pg/node_modules/brainly-scraper-v2/src/main.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/data/data/com.termux/files/home/pg/node_modules/brainly-scraper-v2/src/main.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Note: server udah aku ubah ke id dan ru tapi hasilnya masih error 403 padahal aku nggak pakai proxy apapun.

**Comment by hansputera** [comment]
Coba di kode negaranya kan `id` ya? Coba gunakan kode negara yang lainnya.

**Comment by ThisMe124** [comment]
> Coba di kode negaranya kan `id` ya? Coba gunakan kode negara yang lainnya.
> 
> Daftar kode negara yang tersedia: [LANGUAGES.md](https://github.com/hansputera/brainly-scraper-languages/blob/master/AVAILABLE_LANGUAGES.md)

Gak bisa di Perbaiki Yah?, Saya Juga Mendapatkan Error Yang Sama

**Comment by evaasmakula** [comment]
Kemungkinan error di cors nya axios, atau mungkin dari termux ku. Soalnya tadi aku buat downloader pake axios juga error 🥴

**Comment by ThisMe124** [comment]
> Kemungkinan error di cors nya axios, atau mungkin dari termux ku. Soalnya tadi aku buat downloader pake axios juga error 🥴

Jadi gak iso?

**Comment by evaasmakula** [comment]
> > Kemungkinan error di cors nya axios, atau mungkin dari termux ku. Soalnya tadi aku buat downloader pake axios juga error 🥴
> 
> Jadi gak iso?

Bisa coba aktifkan cors nya disini

https://stackoverflow.com/questions/50949594/axios-having-cors-issue

**Comment by hansputera** [comment]
Kayaknya bukan cors issue deh(?)

**Comment by hansputera** [comment]
![image](https://user-images.githubusercontent.com/47862061/140326941-35dd7453-c8c4-4b8b-aa43-abb12e132405.png)
Kebetulan tadi saya juga lagi coba2 ganti http clientnya ke `axios` ini bisa di akses dari region `Indonesia`

**Comment by hansputera** [comment]
Untuk http client yang sekarang kita masih menggunakan [got](https://npmjs.com/got)

**Comment by hansputera** [comment]
Kebetulan tadi saya ada ide untuk rotate country code.

**Penjelasan:**

Untuk rotate ini sendiri, nanti saya akan dapatkan semua country code.

Kemudian, saya akan lakukan request ke masing2 country code tersebut. Jika responsenya di accept, maka country codenya akan di masukan ke sebuah [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) untuk dijadikan kumpulan kode negara yang akan digunakan kedepannya.

Jika tidak ada yang berhasil, maka kita akan alihkan ke kode negara `id` atau `Indonesia` atau alihkan saja ke sebuah Exception?.

**Comment by ThisMe124** [comment]
> Kebetulan tadi saya ada ide untuk rotate country code.
> 
> **Penjelasan:**
> 
> Untuk rotate ini sendiri, nanti saya akan dapatkan semua country code.
> 
> Kemudian, saya akan lakukan request ke masing2 country code tersebut. Jika responsenya di accept, maka country codenya akan di masukan ke sebuah [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) untuk dijadikan kumpulan kode negara yang akan digunakan kedepannya.
> 
> Jika tidak ada yang berhasil, maka kita akan alihkan ke kode negara `id` atau `Indonesia` atau alihkan saja ke sebuah Exception?.
> 
> Cara ini mungkin akan saya buat sebuah method yang dapat dijalankan manual dan otomatis,,
> 
> untuk otomatis ini kira2 nanti saya akan buat opsi untuk waktu setiap berapa kali menjalankannya dan juga dapat di stop. Method ini berfungsi untuk melakukan **fetching** seperti yang saya jelaskan diatas.
> 
> Setuju?

Se7

**Comment by hansputera** [comment]
Hello everyone! Good evening.

Saya baru baru saya publish package ini ke NPM dengan versi `2.0.6` yang dimana ada sedikit perubahan.
Untuk changelogs nya bisa lihat di pull request terkait #10

**Comment by hansputera** [comment]
Hasil uji tes yang saya lakukan tadi dari server singapore (Virtual Machine), memperlihatkan respons yang cukup bagus, ya beberapa kode negara yang di awal pengecekan itu terlihat bagus.
Namun, di next request menunjukan respons yang tidak bagus seperti `403 Forbidden` yang dimana terkena proteksi [Cloudflare](https://cloudflare.com)
